annotator_gui/annotator_gui/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # path has route, a string that contains a URL pattern and view. 
    # When Django finds a matching pattern, it calls the specified view \
    # function with an HttpRequest object as the first argument and any “captured” \
    # values from the route as keyword arguments
    path('admin/', admin.site.urls),
    path('', include('gui.urls'))
]

annotator_gui/gui/urls.py
from django.urls import include, path

# for favicon
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.conf import settings

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about',views.about,name='about'),
    path('consensus',views.group_consensus,name='group_consensus'),
    path('login',views.user_login,name='user_login'),
    path('logout', views.user_logout, name='user_logout'),
    path('profile', views.user_profile, name='user_profile'),
    path('home',views.annotator_home,name='annotator_home'),
    path('annotate/<int:patient_id>/<int:local_note_id>',views.show_note,name='show_note'),
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")))
]

annotator_gui/gui/models.py
from django.db import models

# to reset databsae:
    # run python manage.py reset_db (from django-extensions package)

# to delete all data from the table:
# python manage.py shell
# >> from gui.models import PatientDemographic, PatientYear, Note
# >> PatientDemographic.objects.all().delete()
# >> PatientYear.objects.all().delete()
# >> Note.objects.all().delete()

# to add data:
# update .csv files in load_data/data
# python manage.py shell
# >> %run load_data/load_data.py


SDChoices = (
('0', 'No Cognitive Concern'),
('1', 'Mild Cognitive Impairment'),
('2', 'Dementia')
)

DSChoices = (
('0', 'None'),
('1', 'Mild'),
('2', 'Moderate'),
('3', 'Severe'),
('9', 'Unknown')
)

LCChoices = (
('0', 'Not Confident'),
('1', 'Mildly Confident'),
('2', 'Moderately Confident'),
('3', 'Highly Confident')
)

LabelChoices = (
('0', 'No Relevant Information'),
('1', 'Relevant to Cognitive Concern')
)


class PatientDemographic(models.Model):
    PatientID = models.IntegerField(blank = True, null = True)
    MRN = models.IntegerField(blank = True, null = True)
    BirthDTS = models.DateField(blank = True, null = True)
    EthnicGroupDSC = models.TextField(blank = True, null = True)
    MaritalStatusDSC = models.TextField(blank = True, null = True)
    SexDSC = models.TextField(blank = True, null = True)
    EducationLevelDSC = models.TextField(blank = True, null = True)
    CoordinationNote = models.TextField(blank = True, null = True)
    PatientLabs = models.TextField(blank = True, null = True)
    PatientImaging = models.TextField(blank = True, null = True)
    Assigned = models.BooleanField(default = False)
    SyndromicDiagnosis = models.TextField(choices = SDChoices, default = 'Incomplete')
    DementiaSeverity = models.TextField(choices = DSChoices, default = 'Incomplete')
    LabelCertainty = models.TextField(choices = LCChoices, default = 'Incomplete')
    Annotator = models.TextField(blank = True, null = True)
    DateAnnotated = models.DateTimeField(blank = True, null = True)
    Scratchpad = models.TextField(blank = True, null = True, default='')
    Consensus = models.BooleanField(default = False)
    ConsensusActor = models.TextField(blank = True, null = True)
    
    def __str__(self):
        return(str(self.PatientID))


class PatientYear(models.Model):
    PatientID = models.IntegerField(blank = True, null = True)
    Year = models.CharField(max_length = 4, blank = True, null = True)
    CurrentMeds = models.TextField(blank = True, null = True)
    MedHistory = models.TextField(blank = True, null = True)
    NoShows = models.IntegerField(blank = True, null = True)
    Cancellations = models.IntegerField(blank = True, null = True)
    NumberNotes = models.IntegerField(blank = True, null = True)
    TotalEncounters = models.IntegerField(blank = True, null = True)
    ICDCodes = models.TextField(blank = True, null = True)
    
    def __str__(self):
        return(str(self.PatientID) + "/" + str(self.Year))


class Note(models.Model):
    PatientID = models.IntegerField(blank = True, null = True)
    PatientEncounterID = models.CharField(max_length = 100, blank = True, null = True)
    InpatientNoteTypeDSC = models.TextField(blank = True, null = True)
    ContactDTS = models.DateField(blank = True, null = True)
    EncounterTypeDSC = models.TextField(blank = True, null = True)
    NoteID = models.IntegerField(blank = True, null = True)
    LocalNoteID = models.IntegerField(blank = True, null = True)
    NoteTXT = models.TextField(blank = True, null = True)
    ProviderNM = models.TextField(blank = True, null = True)
    LicenseDisplayDSC = models.TextField(blank = True, null = True)
    PrimaryDepartmentDSC = models.TextField(blank = True, null = True)
    CurrentPCP = models.TextField(blank = True, null = True)
    Year = models.CharField(max_length = 4, blank = True, null = True)
    KeywordCount = models.IntegerField(blank = True, null = True)
    ImagingInInterval = models.BooleanField(default = False)
    LabsInInterval = models.BooleanField(default = False)
    Label = models.TextField(choices = LabelChoices, default = 'Incomplete')
    Annotator = models.TextField(blank = True, null = True)
    DateAnnotated = models.DateTimeField(blank = True, null = True)

    def __str__(self):
        return(str(self.PatientID) + "/" + str(self.LocalNoteID))

annotator_gui/gui/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
import regex as re
import functools
import datetime
from itertools import chain, cycle
from .models import PatientDemographic, PatientYear, Note
from accounts.forms import NoteForm, SignUpForm, RequestPatientsForm, KeywordForm, PatientForm, ScratchpadForm, ConsensusForm
from django.contrib import messages

#reading in headers
import pandas as pd

# log-in and sign-up forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required


## INDEX VIEW
def index(request):

    # retrieve information of currently logged in user
    current_user = request.user

    # redirect to either annotator home or login page
    if current_user.is_authenticated:
        return redirect('/home')
    else:
        return redirect('/login')


### ABOUT PAGE
def about(request):

     # get template from gui/profile.html
    template = loader.get_template('gui/about.html')

    email_form = "Name:%0D%0AFeature Request:"

    context = {'email_form': email_form}

    return HttpResponse(template.render(context, request))


## USER LOGIN VIEW
def user_login(request):

    # get template from gui/login.html
    template = loader.get_template('gui/login.html')

    # define sign up and log in forms
    signup_form = SignUpForm(request.POST)
    login_form = AuthenticationForm(data=request.POST)

    if request.method == 'POST':

        # check sign up form, log in user
        if signup_form.is_valid():
            user = signup_form.save()
            login(request, user)

            # # upon sign-up, assign five patients
            # unassigned = PatientDemographic.objects.filter(Assigned = False)[0:5]

            # # get patient IDs, update Assigned of PatientDemographic database to True
            # patientIDs = []
            # for patient in unassigned:
            #     patientIDs.append(patient.PatientID)
            #     patient.Assigned = True
            #     patient.save()

            # # save patient IDs in AssignedPatients variable for each user upon login
            # user.AssignedPatients = ', '.join([str(x) for x in patientIDs])
            # print("Patients Assigned: " + user.AssignedPatients)
            user.save()

            return redirect('/home')
        else:
            signup_form = SignUpForm()

        # check log in form
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            print("Log-In Success Message")
            messages.success(request, 'You are now logged in as ' + user.username + '.')
            return redirect('/home')
        else:
            login_form = AuthenticationForm()

        
        print("Sign-Up or Log-In Error Message")
        messages.error(request, 'The credentials entered are invalid. Please try again.')

    context = {
        'signup_form': signup_form,
        'login_form': login_form
    }

    return HttpResponse(template.render(context, request))


### USER LOGOUT
@login_required(redirect_field_name = None)
def user_logout(request):
    # if request.method == 'POST':
    #     logout(request)
    logout(request)    
    return redirect('/login')


### USER PROFILE
@login_required(redirect_field_name = None)
def user_profile(request):

     # get template from gui/profile.html
    template = loader.get_template('gui/profile.html')

    current_user = request.user

    # retrieve and parse assigned IDs
    assignedIDs = current_user.AssignedPatients
    assignedIDs = [int(x) for x in assignedIDs.split(', ')] if assignedIDs != 'None' else [None] # if no patients are assigned (i.e. admin), show patient 1

    full_note_count = Note.objects.filter(PatientID__in = assignedIDs).count()
    full_patient_count = PatientDemographic.objects.filter(PatientID__in = assignedIDs).count()

    # get notes with completed annotations
    noteDB = Note.objects.filter(Annotator = current_user.username)
    annot_patients = []
    for annot_notes in noteDB:
        annot_patients.append(annot_notes.PatientID)
    annot_patients = list(set(annot_patients)) # convert to set to remove duplicate patient IDs

    note_patientDB = PatientDemographic.objects.filter(PatientID__in = annot_patients) # subset patients which have SOME completed notes, NOT ALL COMPLETED PATIENTS
    
    completed_note_count = noteDB.count()
    no_notes = completed_note_count == 0

    # get all completed patients
    patientDB = PatientDemographic.objects.filter(Annotator = current_user.username)

    completed_patient_count = patientDB.count()
    no_patients = completed_patient_count == 0


    # get account keywords
    keywords_raw = current_user.Keywords

    # form to update keywords
    keywords_form = KeywordForm(initial = {'keywords': keywords_raw})
    if request.method == 'POST':
        keywords_form  = KeywordForm(request.POST)
        if keywords_form.is_valid():
            keywords_raw = keywords_form['keywords'].value()
            print("Keywords: " + keywords_raw)
            current_user.Keywords = keywords_raw
            current_user.save()
            messages.success(request, 'Keywords updated for your account.')
            return redirect('/profile')

    context = {
        'current_user': current_user,
        
        'noteDB': noteDB,
        'note_patientDB': note_patientDB,
        'completed_note_count': completed_note_count,
        'full_note_count': full_note_count,
        'no_notes': no_notes,

        'patientDB': patientDB,
        'completed_patient_count': completed_patient_count,
        'full_patient_count': full_patient_count,
        'no_patients': no_patients,

        'keywords_form': keywords_form,
        'keywords_raw': keywords_raw,
    }

    return HttpResponse(template.render(context, request))


### USER PROFILE
@login_required(redirect_field_name = None)
def group_consensus(request):

    # get template from gui/consensus.html
    template = loader.get_template('gui/consensus.html')

    # get note and patient databases
    patientDB = PatientDemographic.objects.filter(Consensus = True) # subset patients which are assigned
    consensusIDs = [x.PatientID for x in patientDB]
    noteDB = Note.objects.filter(PatientID__in = consensusIDs) # subset notes of those patients

    # calculate statistics for notes
    noteTODO = noteDB.filter(Label = "Incomplete")
    total_notes = noteDB.count()
    todo_notes = noteTODO.count()
    completed_notes = total_notes - todo_notes
    notes_per = round(todo_notes / total_notes * 100) if total_notes != 0 else 0

    no_notes = total_notes == 0

    # calculate statistics for patient-year
    patientTODO = patientDB.filter(SyndromicDiagnosis = "Incomplete")
    total_patients = patientDB.count()
    todo_patients = patientTODO.count()
    completed_patients = total_patients - todo_patients
    patients_per = round(todo_patients / total_patients * 100) if total_patients != 0 else 0


    context = {
        'patientDB': patientDB,
        'noteDB': noteDB, 
        'noteTODO': noteTODO, 
        'total_notes': total_notes, 
        'todo_notes': todo_notes, 
        'completed_notes': completed_notes, 
        'notes_per': notes_per, 
        'no_notes': no_notes,
        'patientTODO': patientTODO, 
        'total_patients': total_patients, 
        'todo_patients': todo_patients, 
        'completed_patients': completed_patients, 
        'patients_per': patients_per,
    }

    return HttpResponse(template.render(context, request))
     

## ANNOTATOR HOME VIEW
@login_required(redirect_field_name = None)
def annotator_home(request):
    
    # get template from gui/home.html
    template = loader.get_template('gui/home.html')

    # retrieve information of currently logged in user
    current_user = request.user

    # retrieve and parse assigned IDs
    assignedIDs = current_user.AssignedPatients
    assignedIDs = [int(x) for x in assignedIDs.split(', ')] if assignedIDs != 'None' else [None] # if no patients are assigned (i.e. admin), show patient 1

    # get note and patient databases
    patientDB = PatientDemographic.objects.filter(PatientID__in = assignedIDs) # subset patients which are assigned
    noteDB = Note.objects.filter(PatientID__in = assignedIDs) # subset notes of those patients
    # patientyearDB = PatientYear.objects.filter(PatientID__in = assignedIDs)

    ### CALCULATE STATISTICS FOR DASHBOARD 

    # calculate statistics for notes
    noteTODO = noteDB.filter(Label = "Incomplete")
    total_notes = noteDB.count()
    todo_notes = noteTODO.count()
    completed_notes = total_notes - todo_notes
    notes_per = round(todo_notes / total_notes * 100) if total_notes != 0 else 0

    no_notes = total_notes == 0

    # calculate statistics for patient-year
    patientTODO = patientDB.filter(SyndromicDiagnosis = "Incomplete")
    total_patients = patientDB.count()
    todo_patients = patientTODO.count()
    completed_patients = total_patients - todo_patients
    patients_per = round(todo_patients / total_patients * 100) if total_patients != 0 else 0

    # form to assign additional patients
    form = RequestPatientsForm()
    if request.method == 'POST':
        
        value = RequestPatientsForm(request.POST)

        if value.is_valid():
            num_to_add = int(value['num_to_add'].value()) # get values from POST
            print("Assigning Additional Patients: " + str(num_to_add) + " patients to " + str(current_user))
            # num_to_add = num_to_add-1 if num_to_add > 1 else num_to_add  # remember this is zero-indexed

            # assign additional patients
            unassigned = PatientDemographic.objects.filter(Assigned = False)[0:num_to_add]

            # get patient IDs, update Assigned of PatientDemographic database to True

annotator_gui/gui/templates/gui/about.html
{% extends "./base.html" %}
{% load static %}
{% load notes_filter %}

{% block content %}

<div class="five columns card">

    <div class="bg-white">
        <div class="padding-top-bot">
            <h4>Team</h4>

            <p>The NLP Annotator Tool was developed by the <a href="https://www.massgeneral.org/neurology/research/mind-data-science-lab" target="_blank">MIND Data Science Lab</a> at Massachusetts General Hospital.</p>

            <p><b>Core Developer:</b> <a href="mailto:ttyagi@mgh.harvard.edu">Tanish Tyagi</a></p>

            <p><b>Principal Investigator:</b> <a href="mailto:SDAS5@mgh.harvard.edu">Dr. Sudeshna Das</a></p>

        </div>
    </div>

</div>


<div class="five columns card-left">

    <div class="bg-white">
        <div class="padding-top-bot">
            <h4>Contact</h4>

            <p>Please use the link below to contact our team or request new features.</p>

            <div style="text-align: center; padding-top: 10px;"><a href="mailto:SDAS5@mgh.harvard.edu?cc=ttyagi@mgh.harvard.edu&subject=NLP Annotator Tool &body={{email_form}}"><button class="small-button">Contact</button></a></div>

        </div>
    </div>

</div>

{% endblock content %}

annotator_gui/gui/templates/gui/base.html
{% load static %}

<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="icon"href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="{%  static  'css/base.css'  %}">
    <link rel="stylesheet" href="{%  static  'css/custom.css'  %}">

    <!-- CSS from external sources e.g. boostrap -->
    <link rel="stylesheet" href="{%  static  'css/external.css'  %}">

    <!-- CSS for tablesorter -->
    <link rel="stylesheet" href="{%  static  'css/tablesorter.css'  %}">
    
    <!-- Boostrap CDN -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" rel="nofollow" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous"> -->
    
    <title>NLP Annotator</title>

</head>

<body>

    <div class="title-banner row">
        <div class="title-container">
            <h2 class="h2-title">NLP ANNOTATOR TOOL</h2>
        </div>

        <div class="nav-container"></div>
        {% if user.is_authenticated %}
            <!-- <div class="vl"></div> -->
            <a href="/logout"><button class="button-title">Log Out</button></a>
            <a href="/consensus"><button class="button-title" style="width: 120px;">Consensus</button></a>
            <a href="/about"><button class="button-title">About</button></a>
            <a href="/profile"><button class="button-title">Profile</button></a>
            <a href="/home"><button class="button-title">Home</button></a>
        {% else %}
            <a href="/login"><button class="button-title">Log In</button></a>
            <a href="/about"><button class="button-title">About</button></a>
        {% endif %}
    </div>
    </div>

    {% include './includes/messages.html' %}

    <div class="app-body row">

        {% block content %}

        {% endblock content %}

    </div>

    <!-- load jQuery and tablesorter scripts -->
    <script type="text/javascript" src="{% static 'js/jquery-3.5.1.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/tablesorter/jquery.tablesorter.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/tablesorter/jquery.tablesorter.widgets.js' %}"></script>
    
    <script src="{% static 'js/script.js' %}"></script>

</body>

</html>

annotator_gui/gui/templates/gui/consensus.html
{% extends "./base.html" %}
{% load static %}
{% load notes_filter %}

{% block content %}

<div class="seven columns card">

    <div class="bg-white">
        <div class="padding-top-bot">
            <h4>Consensus Dashboard</h4>
            <table style = "width: 100%;">
                <tr style = "text-align: center;">
                    <th><h5>Note Annotation</h5></th>
                    <th><h5>Patient Annotation</h5></th>
                </tr>
                <tr>
                    <td>
                        <p style = "text-align: left;"><b>Assigned Notes: </b>{{total_notes}}</p>
                        <p style = "text-align: left;"><b>Completed Notes: </b>{{completed_notes}}</p>
                        <p style = "text-align: left; margin-bottom: 0px;"><b>{{notes_per}}% </b>of consensus notes remaining to label.</p>
                    </td>
                    <td>
                        <p style = "text-align: left;"><b>Assigned Patients: </b>{{total_patients}}</p>
                        <p style = "text-align: left;"><b>Completed Patients: </b>{{completed_patients}}</p>
                        <p style = "text-align: left; margin-bottom: 0px;"><b>{{patients_per}}% </b>of consensus patients remaining to annotate.</p>
                    </td>
                </tr>
            </table>
        </div>
    </div>

    <div class="bg-white inside-bottom">
        <div class="padding-top-bot">
            <h4>Consensus Conference</h4>
            <p style = "padding-bottom: 20px;">Welcome to the NLP Annotator Tool. Please select patients to annotate below.</p>

            {% if no_notes %}
            <p style = "padding-bottom: 20px; color: red; font-weight: 800;">No patients are currently assigned. Please use the form on the right to request additional patients to annotate.</p>
            {% endif %}

            {% for patient in patientDB %}

            <button class="collapsible">
                Patient #{{patient.PatientID}} - {{patient|get_age:noteDB}}, {{patient|get_sex}}
            </button>
            <div class="content">
                <table class = "tablesorter" style = "width: 100%" >
                    <thead>
                        <tr>
                            <th>Link</th>
                            <th>Date</th>
                            <th>Encounter Type</th>
                            <th>Provider</th>
                            <th>Department</th>
                            <th>Keywords</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for note in noteDB|filter_note:patient.PatientID %}
                        <tr style="background-color: {{note|fill_table}};">
                            <td><a href="/annotate/{{note.PatientID}}/{{note.LocalNoteID}}#note">{{note.LocalNoteID}}</a></td>
                            <td>{{note.ContactDTS}}</td>
                            <td>{{note.EncounterTypeDSC}}</td>
                            <td>{{note.ProviderNM}}</td>
                            <td>{{note.PrimaryDepartmentDSC}}</td>
                            <td>{{note.KeywordCount}}</td>
                        </tr>                   
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <span class="consensus-actor">Sent to consensus by {{patient.ConsensusActor}}.</span>
            <br>

            {% endfor %}

        </div>
    </div>

</div>


<div class="three columns card-left">

    <div class="bg-white">
        <h4>Welcome</h4>
        <p>Notes sent to consensus are accessible by all annotators. Consensus conferences can be used to review conflicting or challenging notes, as well as flag notes with known issues.</p>
    </div>

    <div class="bg-white inside-bottom">
        <h4>About</h4>
        <p>The NLP Annotator Tool was developed by the <a href="https://www.massgeneral.org/neurology/research/mind-data-science-lab" target="_blank">MIND Data Science Lab</a> at MassGeneral Hospital.</p>
    </div>

</div>

{% endblock content %}

annotator_gui/gui/templates/gui/login.html
{% extends "./base.html" %}
{% load static %}

{% block content %}

<div class="five columns card">

    <div class="bg-white">
        <div class="padding-top-bot">
            <h4>Sign Up</h4>
            <p>Welcome to the NLP Annotator Tool. Please sign-up for our tool below. Please use your Partners username when registering.</p>

            <form method="post">
                {% csrf_token %}
                
                {% for field in signup_form %}
                <p>
                  <br><b>{{ field.label_tag }}</b>
                  {{ field }}
                  {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                  {% endif %}
                  {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                  {% endfor %}
                </p>
                {% endfor %}

                <div style="text-align: center;"><button class="small-button" type="submit">Sign Up</button></div>
            </form>

        </div>
    </div>


</div>


<div class="five columns card-left">

    <div class="bg-white">
        <div class="padding-top-bot">
            <h4>Log In</h4>
            <p>Please log-in to continue annotating.</p>

            <form method="post">
                {% csrf_token %}
                
                {% for field in login_form %}
                <p>
                  <br><b>{{ field.label_tag }}</b>
                  {{ field }}
                  {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                  {% endif %}
                  {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                  {% endfor %}
                </p>
                {% endfor %}

                <div style="text-align: center;"><button class="small-button" type="submit">Log In</button></div>
            </form>

        </div>
    </div>

</div>

{% endblock content %}

annotator_gui/gui/templates/gui/profile.html
{% extends "./base.html" %}
{% load static %}
{% load notes_filter %}

{% block content %}

<div class="three columns card">

    <div class="bg-white">
        <div class="padding-top-bot">
            <h4>Profile</h4>
            <p><b>Name:</b> {{current_user.last_name}}, {{current_user.first_name}}</p>
            <p><b>Username:</b> {{current_user.username}}</p>
            <p><b>Email:</b> {{current_user.email}}</p>
            <p><b>Date Joined:</b> {{current_user.date_joined}}</p>
        </div>
    </div>

    <div class="bg-white inside-bottom">
        <h4>Keywords</h4>
        <p>Update the keywords for your account below. Separate keywords with commas, regex expressions are supported.</p>    
        <form method="post" novalidate>
            {% csrf_token %}
            <div style="text-align: center;">{{ keywords_form }}</div>                
            <div style="text-align: center; padding-top: 15px;"><button class="small-button" type="submit">Update</button></div>
        </form>
        <div style="padding-top: 20px;">
            <p><b>Current Keywords:</b> {{keywords_raw}}</p>
        </div>
    </div>

</div>


<div class="seven columns card-left">

    <div class="bg-white">
        <div class="padding-top-bot">
            <h4>Completed Patients</h4>

            <p>Below are patients which you have completed annotating.</p>
            <p><b>Completed Patients:</b> {{completed_patient_count}}</p>
            <p style = "padding-bottom: 20px;"><b>Total Assigned Patients:</b> {{full_patient_count}}</p>

            {% if no_patients %}
            <p style = "padding-bottom: 20px; color: red; font-weight: 800;">You have not completed any patient annotations yet.</p>
            
            {% else %}

            <table class = "tablesorter" style = "width: 100%">
                <thead>
                    <tr>
                        <th>Patient ID</th>
                        <th>Birth Date</th>
                        <th>Sex</th>
                        <th>Syndromic Diagnosis</th>
                        <th>Dementia Severity</th>
                        <th>Label Certainty</th>
                        <th>Date Annotated</th>
                    </tr>
                </thead>
                <tbody>
                {% for patient in patientDB %}
                    <tr style="background-color: {{patient|fill_py_table}};">
                        <td><a href="/annotate/{{patient.PatientID}}/1#note">{{patient.PatientID}}</a></td>
                        <td>{{patient.BirthDTS}}</td>
                        <td>{{patient.SexDSC}}</td>
                        <td>{{patient.get_SyndromicDiagnosis_display}}</td>
                        <td>{{patient.get_DementiaSeverity_display}}</td>
                        <td>{{patient.get_LabelCertainty_display}}</td>
                        <td>{{patient.DateAnnotated}}</td>
                    </tr>                   
                {% endfor %}
                </tbody>
            </table>

            {% endif %}

        </div>
    </div>

    <div class="bg-white inside-bottom">
        <div class="padding-top-bot">
            <h4>Completed Notes</h4>

            <p>Below are notes which you have completed labelling.</p>
            <p><b>Completed Notes:</b> {{completed_note_count}}</p>
            <p style = "padding-bottom: 20px;"><b>Total Assigned Notes:</b> {{full_note_count}}</p>

            {% if no_notes %}
            <p style = "padding-bottom: 20px; color: red; font-weight: 800;">You have not completed any note annotations yet.</p>
            {% endif %}

            {% for note_patient in note_patientDB %}

            <button class="collapsible">
                Patient #{{note_patient.PatientID}} - {{note_patient|get_age:noteDB}}, {{note_patient|get_sex}}
            </button>
            <div class="content">
                <table class = "tablesorter" style = "width: 100%">
                    <thead>
                        <tr>
                            <th>Link</th>
                            <th>Date</th>
                            <th>Encounter Type</th>
                            <th>Provider</th>
                            <th>Department</th>
                            <th>Date Annotated</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for note in noteDB|filter_note:note_patient.PatientID %}
                        <tr style="background-color: {{note|fill_table}};">
                            <td><a href="/annotate/{{note.PatientID}}/{{note.LocalNoteID}}#note">{{note.LocalNoteID}}</a></td>
                            <td>{{note.ContactDTS}}</td>
                            <td>{{note.EncounterTypeDSC}}</td>
                            <td>{{note.ProviderNM}}</td>
                            <td>{{note.PrimaryDepartmentDSC}}</td>
                            <td>{{note.DateAnnotated}}</td>
                        </tr>                   
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <br>

            {% endfor %}

        </div>
    </div>

</div>

{% endblock content %}